name: UpdateDockerImage

# Eventos que ativarão o workflow UpdateDockerImage
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker build . -t renangas/hello_bot:latest
      - name: Publish
        run: |
          docker push renangas/hello_bot:latest
